ALTER TABLE accounts 
  ADD COLUMN IF NOT EXISTS bank_name text,
  ADD COLUMN IF NOT EXISTS cut_day integer,
  ADD COLUMN IF NOT EXISTS grace_period integer,
  ADD COLUMN IF NOT EXISTS payment_reminder boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS reminder_days_before integer,
  ADD COLUMN IF NOT EXISTS overdue_interest_rate numeric,
  ADD COLUMN IF NOT EXISTS overdue_penalty numeric,
  ADD COLUMN IF NOT EXISTS investment_length text,
  ADD COLUMN IF NOT EXISTS interest_rate numeric,
  ADD COLUMN IF NOT EXISTS due_date date,
  ADD COLUMN IF NOT EXISTS auto_renew boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS reinvest_interest boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS principal numeric,
  ADD COLUMN IF NOT EXISTS apr numeric,
  ADD COLUMN IF NOT EXISTS loan_term text,
  ADD COLUMN IF NOT EXISTS repayment_structure text,
  ADD COLUMN IF NOT EXISTS collateral text,
  ADD COLUMN IF NOT EXISTS late_payment_interest numeric;